### ISSUE TITLE
项目build后，淘宝接口失效404了怎么办

### ISSUE THREAD

**Issue by ziyouzhiyou** [Zzivh/Vue-taobaoServerTimer#2]
项目build后，淘宝接口失效404了怎么办

**Comment by Zzivh** [comment]
我是用来淘宝抢东西的...没想到真的有人需要呀~~~如果要上线的话可以考虑nginx反向代理解决跨域问题, 我等到五一来完善一下项目

**Comment by ziyouzhiyou** [comment]
哈哈哈你设计的很棒，我改了相对路径和用了反向代理后build成功了，但是比北京时间快了一秒多，是接口问题还是淘宝时间本来就快一点
